---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-config/devspaces/instance/overlays/default
    repoURL:  https://github.com/tosin2013/quarkus-holidays-ai.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true